"""ordernn_products

Revision ID: 5491f590d4f4
Revises: 
Create Date: 2023-09-28 15:31:46.506204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5491f590d4f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordernn_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('price', sa.Numeric(decimal_return_scale=1), nullable=True),
    sa.Column('description', sa.String(length=10240), nullable=True),
    sa.Column('characteristics', sa.JSON(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordernn_products_id'), 'ordernn_products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ordernn_products_id'), table_name='ordernn_products')
    op.drop_table('ordernn_products')
    # ### end Alembic commands ###
